created Book model + repository and service layers
validatorr/online-book-store pull request #1
Opened 2023-10-12 17:39 UTC by validatorr

2023-10-12 18:56 UTC, don-bigdad approved these changes
Great job!

2023-10-13 06:38 UTC, Andriy-dz requested changes
Good Job! Lets improve your solution

2023-10-13 06:38 UTC, Andriy-dz commented on src/main/java/v/hryhoryk/onlinebookstore/model/Book.java
> +public class Book {
add table annotation

2023-10-13 06:38 UTC, Andriy-dz commented on src/main/java/v/hryhoryk/onlinebookstore/model/Book.java
> +    private String description;
conditions are missing above the fields (unique, not null)

2023-10-13 11:17 UTC, Elena-Bruyako requested changes
Let's fix some comments.

2023-10-13 11:17 UTC, Elena-Bruyako commented on src/main/java/v/hryhoryk/onlinebookstore/model/Book.java
> +@Table
Let's add the name of table

2023-10-13 11:17 UTC, Elena-Bruyako commented on src/main/java/v/hryhoryk/onlinebookstore/service/BookServiceImpl.java
> +
remove empty line

2023-10-13 11:26 UTC, Elena-Bruyako approved these changes

2023-10-17 09:59 UTC, merged