security dependency and all relevant classes added
validatorr/online-book-store pull request #6
Opened 2023-11-01 14:01 UTC by validatorr

2023-11-01 17:25 UTC, TetianaDenchyk approved these changes

2023-11-02 11:37 UTC, liliia-ponomarenko requested changes
good job! Let’s  fix a few mistakes ;)

2023-11-02 11:37 UTC, liliia-ponomarenko commented on src/main/java/v/hryhoryk/onlinebookstore/dto/UserRegistrationRequestDto.java
> +        String repeatPassword
also, better to provide max length to avoid SQL exceptions

2023-11-02 11:37 UTC, liliia-ponomarenko commented on src/main/java/v/hryhoryk/onlinebookstore/exceptions/CustomGlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(errorResponse);
```suggestion
        return ResponseEntity.status(HttpStatus.CONFLICT).body(errorResponse);
```

2023-11-02 11:37 UTC, liliia-ponomarenko commented on src/main/java/v/hryhoryk/onlinebookstore/security/CustomUserDetailsService.java
> +@Component
```suggestion
@Service 
```

2023-11-02 11:37 UTC, liliia-ponomarenko commented on src/main/java/v/hryhoryk/onlinebookstore/security/CustomUserDetailsService.java
> +    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
```suggestion
    public UserDetails loadUserByUsername(String username)  {
```

2023-11-02 11:37 UTC, liliia-ponomarenko commented on src/main/java/v/hryhoryk/onlinebookstore/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader(AUTHORIZATION_HEADER);
```suggestion
        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
```
you can use this constant

2023-11-02 11:37 UTC, liliia-ponomarenko commented on src/main/java/v/hryhoryk/onlinebookstore/service/user/UserServiceImpl.java
> +        if (userRepository.findByEmail(requestDto.email()).isPresent()) {
better use existsByEmail from JPA repository

2023-11-02 11:37 UTC, liliia-ponomarenko commented on src/main/java/v/hryhoryk/onlinebookstore/validation/FiledMatchValidator.java
> +        }
You can simplify  it `firstFieldValue != null && firstFieldValue.equals(secondFieldValue)`

2023-11-02 11:37 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/02-create-roles-table.yaml
> +                    unique: true
Let’s  add one empty line at the end  of the file (check other files)

2023-11-02 11:37 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +
```suggestion
```

2023-11-04 13:41 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-11-04 13:41 UTC, NazarSmith228 commented on pom.xml
> +            <version>2.1.0</version>
there's `2.2.0` version

2023-11-04 13:41 UTC, NazarSmith228 commented on pom.xml
> +            <scope>test</scope>
you don't need it as of now

2023-11-04 13:41 UTC, NazarSmith228 commented on src/main/java/v/hryhoryk/onlinebookstore/controller/AuthenticationController.java
> +    @ResponseStatus(code = HttpStatus.OK)
just FYI

`OK` is the default response status, so you can omit it

remember about this in future :)

2023-11-04 13:41 UTC, NazarSmith228 commented on src/main/java/v/hryhoryk/onlinebookstore/controller/BookController.java
> +    @PreAuthorize("hasAnyRole('ADMIN', 'USER')")
shouldn't admin user also have a role `USER`?

or you design your app in a way that admin does not have same priviliges as user has?

2023-11-04 13:41 UTC, NazarSmith228 commented on src/main/java/v/hryhoryk/onlinebookstore/dto/UserLoginRequestDto.java
> +        @Email
shouldn't you specify regex here?

will it work as is?

2023-11-04 13:41 UTC, NazarSmith228 commented on src/main/java/v/hryhoryk/onlinebookstore/security/AuthenticationService.java
> +        final Authentication authentication = authenticationManager.authenticate(
```suggestion
        Authentication authentication = authenticationManager.authenticate(
```

2023-11-04 13:41 UTC, NazarSmith228 commented on src/main/java/v/hryhoryk/onlinebookstore/service/user/UserService.java
> +    UserResponseDto register(UserRegistrationRequestDto requestDto) throws RegistrationException;
```suggestion
    UserResponseDto register(UserRegistrationRequestDto requestDto);
```

2023-11-04 13:41 UTC, NazarSmith228 commented on src/main/java/v/hryhoryk/onlinebookstore/service/user/UserServiceImpl.java
> +            throws RegistrationException {
```suggestion
    public UserResponseDto register(UserRegistrationRequestDto requestDto) {
```

2023-11-04 13:41 UTC, NazarSmith228 commented on src/main/java/v/hryhoryk/onlinebookstore/validation/FieldMatch.java
> +    String secondField();
why not specifying :
```
String[] fields()
```
in order to make validation more flexible

2023-11-06 10:52 UTC, liliia-ponomarenko approved these changes
Great! 😊

2023-11-07 06:52 UTC, merged