shopping cart and cart item added
validatorr/online-book-store pull request #8
Opened 2023-11-14 16:02 UTC by validatorr

2023-11-15 08:01 UTC, TetianaDenchyk approved these changes

2023-11-15 08:01 UTC, TetianaDenchyk commented on src/main/java/v/hryhoryk/onlinebookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +        newCartItem.setQuantity(cartItemRequestDto.quantity());
I think it can be done with some mapper

2023-11-15 11:43 UTC, Elena-Bruyako requested changes
Good job! Let's fix some comments.

2023-11-15 11:43 UTC, Elena-Bruyako commented on src/main/java/v/hryhoryk/onlinebookstore/service/shoppingcart/ShoppingCartService.java
> +
remove empty line

2023-11-15 11:43 UTC, Elena-Bruyako commented on src/main/java/v/hryhoryk/onlinebookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +            Authentication authentication, Long cartItemId, CartItemQuantityDto requestDtp) {
```suggestion
            Authentication authentication, Long cartItemId, CartItemQuantityDto requestDto) {
```

2023-11-15 11:43 UTC, Elena-Bruyako commented on src/main/java/v/hryhoryk/onlinebookstore/service/user/UserServiceImpl.java
> +    private UserResponseDto saveUserAndReturnDto(User user) {
looks like this method is redundant, there is no logic that should be in private method

2023-11-15 11:43 UTC, Elena-Bruyako commented on src/main/java/v/hryhoryk/onlinebookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +        User user = (User) userDetailsService.loadUserByUsername(authentication.getName());
I would suggest to create private method for getting User to avoid duplicating code

2023-11-15 11:43 UTC, Elena-Bruyako commented on src/main/java/v/hryhoryk/onlinebookstore/model/ShoppingCart.java
> +    private Set<CartItem> cartItems;
```suggestion
    private Set<CartItem> cartItems = new HashSet<>();
```

2023-11-17 14:14 UTC, Elena-Bruyako approved these changes
Approve. But left one comment

2023-11-17 14:14 UTC, Elena-Bruyako commented on src/main/java/v/hryhoryk/onlinebookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +        User user = (User) userDetailsService.loadUserByUsername(authentication.getName());
```suggestion
        User user = getUser(authentication);
```

2023-11-20 04:28 UTC, closed without merging